# Generated by Django 5.0.4 on 2024-04-08 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allusers',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='Username', max_length=255, null=True)),
                ('fname', models.CharField(blank=True, db_column='FName', max_length=255, null=True)),
                ('lname', models.CharField(blank=True, db_column='LName', max_length=255, null=True)),
                ('isadmin', models.IntegerField(blank=True, db_column='IsAdmin', null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=255, null=True)),
            ],
            options={
                'db_table': 'AllUsers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('biddingid', models.AutoField(db_column='BiddingID', primary_key=True, serialize=False)),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=2, max_digits=10, null=True)),
                ('biddingtime', models.TimeField(blank=True, db_column='BiddingTime', null=True)),
            ],
            options={
                'db_table': 'Bidding',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartid', models.AutoField(db_column='CartID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Checkoutinformation',
            fields=[
                ('checkoutid', models.AutoField(db_column='CheckoutID', primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('username', models.CharField(blank=True, db_column='Username', max_length=255, null=True)),
                ('preferredpayment', models.CharField(blank=True, db_column='PreferredPayment', max_length=255, null=True)),
                ('edittime', models.TimeField(blank=True, db_column='EditTime', null=True)),
            ],
            options={
                'db_table': 'CheckoutInformation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemid', models.AutoField(db_column='ItemID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=255, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('imageurl', models.TextField(blank=True, db_column='ImageURL', null=True)),
                ('posteddate', models.DateField(blank=True, db_column='PostedDate', null=True)),
                ('startingprice', models.DecimalField(blank=True, db_column='StartingPrice', decimal_places=2, max_digits=10, null=True)),
                ('startingtime', models.TimeField(blank=True, db_column='StartingTime', null=True)),
                ('endtime', models.TimeField(blank=True, db_column='EndTime', null=True)),
            ],
            options={
                'db_table': 'Item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageid', models.AutoField(db_column='MessageID', primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
                ('timestamp', models.DateTimeField(blank=True, db_column='Timestamp', null=True)),
            ],
            options={
                'db_table': 'Message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationid', models.AutoField(db_column='NotificationID', primary_key=True, serialize=False)),
                ('startingtime', models.DateTimeField(blank=True, db_column='StartingTime', null=True)),
            ],
            options={
                'db_table': 'Notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordertable',
            fields=[
                ('orderid', models.AutoField(db_column='OrderID', primary_key=True, serialize=False)),
                ('finalprice', models.DecimalField(blank=True, db_column='FinalPrice', decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=255, null=True)),
                ('deliverymethod', models.CharField(blank=True, db_column='DeliveryMethod', max_length=255, null=True)),
                ('upsno', models.CharField(blank=True, db_column='UPSNo', max_length=255, null=True)),
                ('orderid1', models.IntegerField(blank=True, db_column='OrderID1', null=True)),
                ('updatetime', models.DateTimeField(blank=True, db_column='UpdateTime', null=True)),
            ],
            options={
                'db_table': 'OrderTable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('ratingid', models.AutoField(db_column='RatingID', primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, db_column='Score', null=True)),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
            ],
            options={
                'db_table': 'Rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Upstracking',
            fields=[
                ('trackingid', models.AutoField(db_column='TrackingID', primary_key=True, serialize=False)),
                ('upsno', models.CharField(blank=True, db_column='UPSNo', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=255, null=True)),
                ('updatetime', models.DateTimeField(blank=True, db_column='UpdateTime', null=True)),
            ],
            options={
                'db_table': 'UPSTracking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Adminuser',
            fields=[
                ('userid', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dbapp.allusers')),
                ('role', models.CharField(blank=True, db_column='Role', max_length=255, null=True)),
            ],
            options={
                'db_table': 'AdminUser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Normaluser',
            fields=[
                ('userid', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dbapp.allusers')),
                ('profile', models.CharField(blank=True, db_column='Profile', max_length=255, null=True)),
                ('averagerating', models.DecimalField(blank=True, db_column='AverageRating', decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'NormalUser',
                'managed': False,
            },
        ),
    ]
