# Generated by Django 5.0.4 on 2024-04-08 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allusers',
            options={'managed': True},
        ),
    ]
